title: Grünwald lab
email: niklaus.grunwald@oregonstate.edu
description: > # this means to ignore newlines until "baseurl:"
  Research on the epidemiology, genomics and evolution of Phytophthora pathogens.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://grunwald.github.io # the base hostname & protocol for your site
twitter_username: PhytophthoraLab
github_username:  grunwald

# Build settings
markdown: kramdown
theme: minima
